return {
    -- {
    --     "rose-pine/neovim",
    --     name = "rose-pine",
    --     config = function()
    --         require("rose-pine").setup({
    --             disable_background = true,
    --             disable_float_background = true,
    --         })
    --         vim.cmd.colorscheme("rose-pine")
    --         vim.api.nvim_set_hl(0, "NormalNc", { bg = "None" })
    --     end,
    -- },
    -- {
    --     "folke/tokyonight.nvim",
    --     name = "tokyonight",
    --     lazy = false,
    --     priority = 1000,
    --     config = function()
    --         require("tokyonight").setup({
    --             style = "moon",
    --             transparent = true,
    --             terminal_colors = true,
    --         })
    --         vim.cmd.colorscheme("tokyonight")
    --         vim.api.nvim_set_hl(0, "NormalNc", { bg = "None" })
    --     end
    -- }
}
